// Generated by jextract

package com.littlekt.wgpu;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct WGPUQuerySetDescriptorExtras {
 *     WGPUChainedStruct chain;
 *     const WGPUPipelineStatisticName *pipelineStatistics;
 *     size_t pipelineStatisticCount;
 * }
 * }
 */
public class WGPUQuerySetDescriptorExtras {

    WGPUQuerySetDescriptorExtras() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        WGPUChainedStruct.layout().withName("chain"),
        WGPU.C_POINTER.withName("pipelineStatistics"),
        WGPU.C_LONG_LONG.withName("pipelineStatisticCount")
    ).withName("WGPUQuerySetDescriptorExtras");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout chain$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("chain"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static final GroupLayout chain$layout() {
        return chain$LAYOUT;
    }

    private static final long chain$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static final long chain$offset() {
        return chain$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static MemorySegment chain(MemorySegment struct) {
        return struct.asSlice(chain$OFFSET, chain$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUChainedStruct chain
     * }
     */
    public static void chain(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, chain$OFFSET, chain$LAYOUT.byteSize());
    }

    private static final AddressLayout pipelineStatistics$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("pipelineStatistics"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const WGPUPipelineStatisticName *pipelineStatistics
     * }
     */
    public static final AddressLayout pipelineStatistics$layout() {
        return pipelineStatistics$LAYOUT;
    }

    private static final long pipelineStatistics$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const WGPUPipelineStatisticName *pipelineStatistics
     * }
     */
    public static final long pipelineStatistics$offset() {
        return pipelineStatistics$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const WGPUPipelineStatisticName *pipelineStatistics
     * }
     */
    public static MemorySegment pipelineStatistics(MemorySegment struct) {
        return struct.get(pipelineStatistics$LAYOUT, pipelineStatistics$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const WGPUPipelineStatisticName *pipelineStatistics
     * }
     */
    public static void pipelineStatistics(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(pipelineStatistics$LAYOUT, pipelineStatistics$OFFSET, fieldValue);
    }

    private static final OfLong pipelineStatisticCount$LAYOUT = (OfLong)$LAYOUT.select(groupElement("pipelineStatisticCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t pipelineStatisticCount
     * }
     */
    public static final OfLong pipelineStatisticCount$layout() {
        return pipelineStatisticCount$LAYOUT;
    }

    private static final long pipelineStatisticCount$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t pipelineStatisticCount
     * }
     */
    public static final long pipelineStatisticCount$offset() {
        return pipelineStatisticCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t pipelineStatisticCount
     * }
     */
    public static long pipelineStatisticCount(MemorySegment struct) {
        return struct.get(pipelineStatisticCount$LAYOUT, pipelineStatisticCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t pipelineStatisticCount
     * }
     */
    public static void pipelineStatisticCount(MemorySegment struct, long fieldValue) {
        struct.set(pipelineStatisticCount$LAYOUT, pipelineStatisticCount$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

