// Generated by jextract

package com.littlekt.wgpu;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct WGPUPipelineLayoutDescriptor {
 *     const WGPUChainedStruct *nextInChain;
 *     const char *label;
 *     size_t bindGroupLayoutCount;
 *     const WGPUBindGroupLayout *bindGroupLayouts;
 * }
 * }
 */
public class WGPUPipelineLayoutDescriptor {

    WGPUPipelineLayoutDescriptor() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        WGPU.C_POINTER.withName("nextInChain"),
        WGPU.C_POINTER.withName("label"),
        WGPU.C_LONG_LONG.withName("bindGroupLayoutCount"),
        WGPU.C_POINTER.withName("bindGroupLayouts")
    ).withName("WGPUPipelineLayoutDescriptor");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout nextInChain$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("nextInChain"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const WGPUChainedStruct *nextInChain
     * }
     */
    public static final AddressLayout nextInChain$layout() {
        return nextInChain$LAYOUT;
    }

    private static final long nextInChain$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const WGPUChainedStruct *nextInChain
     * }
     */
    public static final long nextInChain$offset() {
        return nextInChain$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const WGPUChainedStruct *nextInChain
     * }
     */
    public static MemorySegment nextInChain(MemorySegment struct) {
        return struct.get(nextInChain$LAYOUT, nextInChain$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const WGPUChainedStruct *nextInChain
     * }
     */
    public static void nextInChain(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(nextInChain$LAYOUT, nextInChain$OFFSET, fieldValue);
    }

    private static final AddressLayout label$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("label"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *label
     * }
     */
    public static final AddressLayout label$layout() {
        return label$LAYOUT;
    }

    private static final long label$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *label
     * }
     */
    public static final long label$offset() {
        return label$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *label
     * }
     */
    public static MemorySegment label(MemorySegment struct) {
        return struct.get(label$LAYOUT, label$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *label
     * }
     */
    public static void label(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(label$LAYOUT, label$OFFSET, fieldValue);
    }

    private static final OfLong bindGroupLayoutCount$LAYOUT = (OfLong)$LAYOUT.select(groupElement("bindGroupLayoutCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t bindGroupLayoutCount
     * }
     */
    public static final OfLong bindGroupLayoutCount$layout() {
        return bindGroupLayoutCount$LAYOUT;
    }

    private static final long bindGroupLayoutCount$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t bindGroupLayoutCount
     * }
     */
    public static final long bindGroupLayoutCount$offset() {
        return bindGroupLayoutCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t bindGroupLayoutCount
     * }
     */
    public static long bindGroupLayoutCount(MemorySegment struct) {
        return struct.get(bindGroupLayoutCount$LAYOUT, bindGroupLayoutCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t bindGroupLayoutCount
     * }
     */
    public static void bindGroupLayoutCount(MemorySegment struct, long fieldValue) {
        struct.set(bindGroupLayoutCount$LAYOUT, bindGroupLayoutCount$OFFSET, fieldValue);
    }

    private static final AddressLayout bindGroupLayouts$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("bindGroupLayouts"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const WGPUBindGroupLayout *bindGroupLayouts
     * }
     */
    public static final AddressLayout bindGroupLayouts$layout() {
        return bindGroupLayouts$LAYOUT;
    }

    private static final long bindGroupLayouts$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const WGPUBindGroupLayout *bindGroupLayouts
     * }
     */
    public static final long bindGroupLayouts$offset() {
        return bindGroupLayouts$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const WGPUBindGroupLayout *bindGroupLayouts
     * }
     */
    public static MemorySegment bindGroupLayouts(MemorySegment struct) {
        return struct.get(bindGroupLayouts$LAYOUT, bindGroupLayouts$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const WGPUBindGroupLayout *bindGroupLayouts
     * }
     */
    public static void bindGroupLayouts(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(bindGroupLayouts$LAYOUT, bindGroupLayouts$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

