// Generated by jextract

package com.littlekt.wgpu;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct WGPUPushConstantRange {
 *     WGPUShaderStageFlags stages;
 *     uint32_t start;
 *     uint32_t end;
 * }
 * }
 */
public class WGPUPushConstantRange {

    WGPUPushConstantRange() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        WGPU.C_INT.withName("stages"),
        WGPU.C_INT.withName("start"),
        WGPU.C_INT.withName("end")
    ).withName("WGPUPushConstantRange");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt stages$LAYOUT = (OfInt)$LAYOUT.select(groupElement("stages"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUShaderStageFlags stages
     * }
     */
    public static final OfInt stages$layout() {
        return stages$LAYOUT;
    }

    private static final long stages$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUShaderStageFlags stages
     * }
     */
    public static final long stages$offset() {
        return stages$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUShaderStageFlags stages
     * }
     */
    public static int stages(MemorySegment struct) {
        return struct.get(stages$LAYOUT, stages$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUShaderStageFlags stages
     * }
     */
    public static void stages(MemorySegment struct, int fieldValue) {
        struct.set(stages$LAYOUT, stages$OFFSET, fieldValue);
    }

    private static final OfInt start$LAYOUT = (OfInt)$LAYOUT.select(groupElement("start"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t start
     * }
     */
    public static final OfInt start$layout() {
        return start$LAYOUT;
    }

    private static final long start$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t start
     * }
     */
    public static final long start$offset() {
        return start$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t start
     * }
     */
    public static int start(MemorySegment struct) {
        return struct.get(start$LAYOUT, start$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t start
     * }
     */
    public static void start(MemorySegment struct, int fieldValue) {
        struct.set(start$LAYOUT, start$OFFSET, fieldValue);
    }

    private static final OfInt end$LAYOUT = (OfInt)$LAYOUT.select(groupElement("end"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t end
     * }
     */
    public static final OfInt end$layout() {
        return end$LAYOUT;
    }

    private static final long end$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t end
     * }
     */
    public static final long end$offset() {
        return end$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t end
     * }
     */
    public static int end(MemorySegment struct) {
        return struct.get(end$LAYOUT, end$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t end
     * }
     */
    public static void end(MemorySegment struct, int fieldValue) {
        struct.set(end$LAYOUT, end$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

