// Generated by jextract

package com.littlekt.wgpu;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct WGPUComputePassTimestampWrites {
 *     WGPUQuerySet querySet;
 *     uint32_t beginningOfPassWriteIndex;
 *     uint32_t endOfPassWriteIndex;
 * }
 * }
 */
public class WGPUComputePassTimestampWrites {

    WGPUComputePassTimestampWrites() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        WGPU.C_POINTER.withName("querySet"),
        WGPU.C_INT.withName("beginningOfPassWriteIndex"),
        WGPU.C_INT.withName("endOfPassWriteIndex")
    ).withName("WGPUComputePassTimestampWrites");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout querySet$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("querySet"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUQuerySet querySet
     * }
     */
    public static final AddressLayout querySet$layout() {
        return querySet$LAYOUT;
    }

    private static final long querySet$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUQuerySet querySet
     * }
     */
    public static final long querySet$offset() {
        return querySet$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUQuerySet querySet
     * }
     */
    public static MemorySegment querySet(MemorySegment struct) {
        return struct.get(querySet$LAYOUT, querySet$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUQuerySet querySet
     * }
     */
    public static void querySet(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(querySet$LAYOUT, querySet$OFFSET, fieldValue);
    }

    private static final OfInt beginningOfPassWriteIndex$LAYOUT = (OfInt)$LAYOUT.select(groupElement("beginningOfPassWriteIndex"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t beginningOfPassWriteIndex
     * }
     */
    public static final OfInt beginningOfPassWriteIndex$layout() {
        return beginningOfPassWriteIndex$LAYOUT;
    }

    private static final long beginningOfPassWriteIndex$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t beginningOfPassWriteIndex
     * }
     */
    public static final long beginningOfPassWriteIndex$offset() {
        return beginningOfPassWriteIndex$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t beginningOfPassWriteIndex
     * }
     */
    public static int beginningOfPassWriteIndex(MemorySegment struct) {
        return struct.get(beginningOfPassWriteIndex$LAYOUT, beginningOfPassWriteIndex$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t beginningOfPassWriteIndex
     * }
     */
    public static void beginningOfPassWriteIndex(MemorySegment struct, int fieldValue) {
        struct.set(beginningOfPassWriteIndex$LAYOUT, beginningOfPassWriteIndex$OFFSET, fieldValue);
    }

    private static final OfInt endOfPassWriteIndex$LAYOUT = (OfInt)$LAYOUT.select(groupElement("endOfPassWriteIndex"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t endOfPassWriteIndex
     * }
     */
    public static final OfInt endOfPassWriteIndex$layout() {
        return endOfPassWriteIndex$LAYOUT;
    }

    private static final long endOfPassWriteIndex$OFFSET = 12;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t endOfPassWriteIndex
     * }
     */
    public static final long endOfPassWriteIndex$offset() {
        return endOfPassWriteIndex$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t endOfPassWriteIndex
     * }
     */
    public static int endOfPassWriteIndex(MemorySegment struct) {
        return struct.get(endOfPassWriteIndex$LAYOUT, endOfPassWriteIndex$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t endOfPassWriteIndex
     * }
     */
    public static void endOfPassWriteIndex(MemorySegment struct, int fieldValue) {
        struct.set(endOfPassWriteIndex$LAYOUT, endOfPassWriteIndex$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

