package com.littlekt.graphics.webgpu

import com.littlekt.util.jsObject

actual fun GPUBindGroupEntry() = jsObject().unsafeCast<GPUBindGroupEntry>()
actual fun GPUObjectBase() = jsObject().unsafeCast<GPUObjectBase>()
actual fun GPURequestAdapterOptions() = jsObject().unsafeCast<GPURequestAdapterOptions>()
actual fun JsRequiredLimits() = jsObject().unsafeCast<JsRequiredLimits>()
actual fun GPUDeviceDescriptor() = jsObject().unsafeCast<GPUDeviceDescriptor>()
actual fun GPUCanvasConfiguration() = jsObject().unsafeCast<GPUCanvasConfiguration>()
actual fun GPUShaderModuleDescriptor() = jsObject().unsafeCast<GPUShaderModuleDescriptor>()
actual fun GPUPipelineLayoutDescriptor() = jsObject().unsafeCast<GPUPipelineLayoutDescriptor>()
actual fun GPURenderPipelineDescriptor() = jsObject().unsafeCast<GPURenderPipelineDescriptor>()
actual fun GPUProgrammableStage() = jsObject().unsafeCast<GPUProgrammableStage>()
actual fun GPUVertexState() = jsObject().unsafeCast<GPUVertexState>()
actual fun GPUVertexBufferLayout() = jsObject().unsafeCast<GPUVertexBufferLayout>()
actual fun GPUVertexAttribute() = jsObject().unsafeCast<GPUVertexAttribute>()
actual fun GPUPrimitiveState() = jsObject().unsafeCast<GPUPrimitiveState>()
actual fun GPUDepthStencilState() = jsObject().unsafeCast<GPUDepthStencilState>()
actual fun GPUStencilFaceState() = jsObject().unsafeCast<GPUStencilFaceState>()
actual fun GPUMultisampleState() = jsObject().unsafeCast<GPUMultisampleState>()
actual fun GPUFragmentState() = jsObject().unsafeCast<GPUFragmentState>()
actual fun GPUColorTargetState() = jsObject().unsafeCast<GPUColorTargetState>()
actual fun GPUBlendState() = jsObject().unsafeCast<GPUBlendState>()
actual fun GPUBlendComponent() = jsObject().unsafeCast<GPUBlendComponent>()
actual fun GPUBufferDescriptor() = jsObject().unsafeCast<GPUBufferDescriptor>()
actual fun GPUBindGroupLayoutDescriptor() = jsObject().unsafeCast<GPUBindGroupLayoutDescriptor>()
actual fun GPUBindGroupLayoutEntry() = jsObject().unsafeCast<GPUBindGroupLayoutEntry>()
actual fun GPUBufferBindingLayout() = jsObject().unsafeCast<GPUBufferBindingLayout>()
actual fun GPUBufferSamplerBindingLayout() = jsObject().unsafeCast<GPUBufferSamplerBindingLayout>()
actual fun GPUTextureBindingLayout() = jsObject().unsafeCast<GPUTextureBindingLayout>()
actual fun GPUBindGroupDescriptor() = jsObject().unsafeCast<GPUBindGroupDescriptor>()
actual fun GPUSamplerDescriptor() = jsObject().unsafeCast<GPUSamplerDescriptor>()
actual fun GPUComputePipelineDescriptor() = jsObject().unsafeCast<GPUComputePipelineDescriptor>()
actual fun GPUTextureDescriptor() = jsObject().unsafeCast<GPUTextureDescriptor>()
actual fun GPUExtent3D() = jsObject().unsafeCast<GPUExtent3D>()
actual fun GPUTextureViewDescriptor() = jsObject().unsafeCast<GPUTextureViewDescriptor>()
actual fun GPURenderPassDescriptor() = jsObject().unsafeCast<GPURenderPassDescriptor>()
actual fun GPURenderPassColorAttachment() = jsObject().unsafeCast<GPURenderPassColorAttachment>()
actual fun GPURenderPassDepthStencilAttachment() = jsObject().unsafeCast<GPURenderPassDepthStencilAttachment>()
actual fun GPUImageCopyTexture() = jsObject().unsafeCast<GPUImageCopyTexture>()
actual fun GPUImageCopyExternalImage() = jsObject().unsafeCast<GPUImageCopyExternalImage>()
actual fun GPUOrigin3D() = jsObject().unsafeCast<GPUOrigin3D>()
actual fun GPUImageDataLayout() = jsObject().unsafeCast<GPUImageDataLayout>()
actual fun GPUImageCopyBuffer() = jsObject().unsafeCast<GPUImageCopyBuffer>()